title: [Samuel Olowo]
logo: samuel.jpg
description: I am a Data Analyst skilled in transforming complex datasets into actionable insights for business decisions. Proficient in Excel, SQL, Power BI, Microsoft Office, and data manipulation, I bring strong analytical solutions and am ready to support the success of dynamic organizations.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
