title: [Samuel Olowo]
logo: samuel.jpg
description: I am a Data Analyst with a wealth of experience in working with diverse data sources and transforming complex datasets into actionable insights that support informed decision-making. 
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
