title: Samuel Olowo
logo: samuel.jpeg
description: With about two years of experience in data analysis, I excel in working with diverse data sources and
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
